
version: "3.7"
services:
  wog-test:
    image: docker.io/amitk3293/wog-flask:v1
    volumes:
      - .:/app/
    depends_on:
      - wog
    ports:
      - 5000:5000
  wog:
    image: docker.io/amitk3293/wog-app:v1
    volumes:
      - .:/app
    command: echo "World of Games - by Amit Karni" 
    ports:
      - 8000:8000
